version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: africaBank
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
