#version: '3.1'
#
#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      POSTGRES_DB: africaBank
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: diagaraf
#    ports:
#      - '5432:5432'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=africaBank'
      - 'POSTGRES_PASSWORD=diagaraf'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'


#  pgadmin4:
#    image: elestio/pgadmin:${SOFTWARE_VERSION_TAG}
#    restart: always
#    environment:
#    PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
#    PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
#    PGADMIN_LISTEN_PORT: 8080
#    ports:
#      - "172.17.0.1:8080:8080"
#    volumes:
#      - ./servers.json:/pgadmin4/servers.json