version: '3.1'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: africaBank
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@africabank.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
