services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    networks:
      - db_network
    restart: unless-stopped
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./docker_volumes/postgres_13:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    pgadmin:
      image: dpage/pgadmin4
      restart: unless-stopped
      networks:
        - db_network
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - '127.0.0.1:5050:80'
